language: python
python:
  - "3.4"
before_install:
  - sudo apt-get install ruby rubygems ruby-dev
  - sudo apt-get install tree
  - sudo gem install asciidoctor
  - sudo gem install coderay
  - git config --global user.name "Travis CI"
  - git config --global user.name "travis@example.com"
  - sudo locale-gen en_GB.UTF-8
  - sudo sed -i s/640x480x8/1280x1024x16/ /usr/bin/xvfb-run

env:
    global:
      - LC_ALL=en_GB.UTF-8

install: "pip install -r requirements.txt"
script:
    - xvfb-run make silent_test_chapter_01
    - xvfb-run make silent_test_chapter_02_unittest
    - xvfb-run make silent_test_chapter_unit_test_first_view
    - xvfb-run make silent_test_chapter_philosophy_and_refactoring
    - xvfb-run make silent_test_chapter_post_and_database
    - xvfb-run make silent_test_chapter_explicit_waits_1
    - xvfb-run make silent_test_chapter_working_incrementally
    - xvfb-run make silent_test_chapter_automate_deployment_with_fabric
    - xvfb-run make silent_test_chapter_database_layer_validation
    - xvfb-run make silent_test_chapter_simple_form
    - xvfb-run make silent_test_chapter_javascript
    - xvfb-run make silent_test_chapter_15
    - xvfb-run make silent_test_chapter_16
    - xvfb-run make silent_test_chapter_17
    - xvfb-run make silent_test_chapter_18
    - xvfb-run make silent_test_chapter_19

