language: python

dist: xenial

python:
  - "3.8"

git:
  submodules: false

before_install:
  - sudo apt update -y
  - sudo apt install -y ruby rubygems ruby-dev tree firefox firefox-geckodriver
  - sudo gem install asciidoctor coderay
  - git config --global user.name "Travis CI"
  - git config --global user.name "travis@example.com"
  - sudo locale-gen en_GB.UTF-8
  - sudo sed -i s/640x480x8/1280x1024x16/ /usr/bin/xvfb-run
  - sed -i 's_git@github.com:_https://github.com/_' .gitmodules
  - git submodule update --init --recursive

env:
  global:
    - LC_ALL=en_GB.UTF-8
    - LANG=en_GB

install: "pip install -r requirements.txt"

script:
  # - xvfb-run make test_chapter_01
  - xvfb-run make test_chapter_02_unittest
  - xvfb-run make test_chapter_03_unit_test_first_view
  # - xvfb-run make test_chapter_04_philosophy_and_refactoring
  # - xvfb-run make test_chapter_05_post_and_database
  # - xvfb-run make test_chapter_06_explicit_waits_1
  # - xvfb-run make test_chapter_07_working_incrementally
  # - xvfb-run make test_chapter_automate_deployment_with_fabric
  # - xvfb-run make test_chapter_database_layer_validation
  # - xvfb-run make test_chapter_simple_form
  # - xvfb-run make test_chapter_javascript
  # - xvfb-run make test_chapter_deploying_validation
  # - xvfb-run make test_chapter_spiking_custom_auth
  # - xvfb-run make test_chapter_mocking
  # - xvfb-run make test_chapter_server_side_debugging
  # - xvfb-run make test_chapter_outside_in

